apiVersion: v1
appVersion: "1.0"
description: A Helm chart for adoption-backend-service app
name: adoption-backend
home: https://github.com/hmcts/adoption-backend
version: 0.0.4
maintainers:
  - name: HMCTS Adoption Team
